### PR TITLE
Add a function to submit posts to subreddits

### PR DESCRIPTION
**Pull request by eudoxia0**
I've tested it with my account, and it can post both text (`self`) and link posts. It doesn't check for errors in the JSON output, and doesn't handle any of the CAPTCHA stuff (I didn't find any documentation describing how that's done, but an account with good karma can post without it).

### CODE REVIEW

**Comment by jperson** [comment]
Could `api-submit` be defined with the [def-post-api](https://github.com/jperson/cl-reddit/blob/master/util.lisp#L99) macro?  It looks like it's doing the same thing as the macro but just needs a couple changes to `def-post-api` to make it work.

**Comment by eudoxia0** [comment]
I tried it, but decided to write the quick version rather than modify the macro.

**Comment by jperson** [comment]
What problem did you have with the macro?

**Comment by eudoxia0** [comment]
Nothing really, I just thought it would be faster to write a regular function.

**Comment by jperson** [comment]
I'd like to keep the code consistent.

Adding the 3 lines to `api-post-generic`
```lisp
,(when sr `(push `("sr" . ,sr) ,params))
,(when kind `(push `("kind" . ,kind) ,params))
,(when title `(push `("title" . ,title) ,params))
```
and changing the macro params to
```lisp
(defmacro api-post-generic (url user &key subreddit action id thing-id text vote spam flair-enabled sr kind title)
```

should be all that's needed.

The whole thing would look like:
```lisp
(defmacro api-post-generic (url user &key subreddit action id thing-id text vote spam flair-enabled sr kind title)
"Defines generic post request"
(let ((params (gensym)) (result (gensym)))
`(let ((,params nil))
,(when subreddit `(push `("sr_name" . ,subreddit) ,params))
,(when sr `(push `("sr" . ,sr) ,params))
,(when kind `(push `("kind" . ,kind) ,params))
,(when title `(push `("title" . ,title) ,params))
,(when action `(push `("action" . ,(symbol-string ,action)) ,params))
,(when id `(push `("id" . ,id) ,params))
,(when thing-id `(push `("thing_id" . ,thing-id) ,params))
,(when text `(push `("text" . ,text) ,params))
,(when vote `(push `("dir" . ,(symbol-string ,vote)) ,params))
,(when spam `(push `("spam" . ,(if ,spam "1" "0")) ,params))
,(when flair-enabled `(push `("flair_enabled" . ,(if ,flair-enabled "1" "0")) ,params))
(push `("api_type" . "json") ,params)
(push `("uh" . ,(user-modhash ,user)) ,params)
(post-request ,url ,user ,params))))
```

Then the `api-submit` function would be defined as
```lisp
;; comment describing this api function
(def-post-api submit &key sr kind text title)
```

**Comment by jperson** [comment]
Closing as unresponsive.

**Pull request closed without merging**
